### ISSUE TITLE
Logout not logging off the current user

### ISSUE THREAD

**Issue by nimisha84** [oflahero/QuickBooksAppMVC5#1] opened 2017-01-26 22:55 UTC
Hi There,

I'm from Intuit and since you asked us to share your sample app with devs, I wanted to see if you can fix this issue related to Logout/Logoff? Once I'm  logged in->Click Logoff and then try to login with another userid, I get to my original logged in screen.
Can you correct that and share update on this issue when you can? 
I will get it published to our docs then.

Thanks,
Nimisha
IDG

**Comment by oflahero** [comment] 2017-01-27 00:25
Hi Nimisha,

Thanks for getting in touch. What you're describing is - as I understand it
- expected behaviour. The user is logging in via OAuth2 (well, actually OpenID) to the sample app,
whereby Intuit itself is doing the authentication on its behalf. So, by
logging into the sample app for the first time in a session, you're also
logging into your Intuit account. You can verify this by logging into the
sample app, then opening a new tab and going to (developer.)intuit.com and
you'll see that you're logged in there too.

So when you log out of the sample app, you're still logged into your Intuit
account itself. If you then try to log back into the sample app, it detects
that you're already authenticated with Intuit and takes you straight in.
This is the sort of behaviour you expect when mucking about on the web and
you see a 'Log in with Facebook' button on some site, and you're already on
Facebook on another tab, so clicking on that button brings you straight in.

To log in as someone else, first log out of your Intuit account, and try
again.

See how you get on and let me know if you've any other questions (or if
I've missed something!)

cheers, Owen

**Comment by oflahero** [comment] 2017-01-31 14:48
Did the earlier comment address the issue, Nimisha? If so, I'll close it - otherwise let me know shortly. Thanks, Owen

**Comment by nimisha84** [comment] 2017-01-31 23:06
Thanks for your comment. I agree with your answer. Please close. I am a bit busy with other projects. Will compare and update you as soon as I can.

**Comment by nimisha84** [comment] 2017-02-13 04:14
Sorry for coming back late on this. I checked and compared this with the other sample apps we have. On logout, we call this func internally to logout the user from Intuit also-
https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/sso_management_api#/logout()

This is a webforms old sample app. You can check it for reference. 
https://github.com/IntuitDeveloper/QuickbooksV3API-DotNet

**Comment by oflahero** [comment] 2017-02-13 11:08
Interesting, I see that's because the sample app doesn't maintain its own
user store and relies on OpenID alone to maintain session variables that
mimic an authorisation context in ASP.NET.

I can change my implementation to include this ipp.anywhere.logout() call,
I don't mind. This is definitely expected behaviour though, right? So if
I'm logged into my Quickbooks company account on one tab, and my sample app
on another tab, I click logout on my app - this will also sign me out of my
main company page too. This is OK?

**Comment by nimisha84** [comment] 2017-02-13 18:00
Yes, most of our sample apps do not have user store so that developers have the flexibility to implement the way they want it.

Regarding this-
So if
I'm logged into my Quickbooks company account on one tab, and my sample app
on another tab, I click logout on my app - this will also sign me out of my
main company page too. This is OK?

Nimisha- Yes, that should sign you out of the main company page too. That is correct.

**Comment by oflahero** [comment] 2017-02-15 13:26
Logout now includes all Intuit accounts also. (Commit b90b2226)

**Comment by nimisha84** [comment] 2017-02-15 18:53
Thanks, will do a pull ->review and get the docs updated to include your sample app.

**Closed as completed** 2017-10-24 20:07 UTC
